Fix NPE when executing parallel module builds
jenkinsci/maven-interceptors pull request #10
Opened 2016-12-16 20:54 UTC by eljonny

I believe I've discovered an issue; this could be because no one has used this feature before?
I enabled "Build Modules in Parallel" and my build failed consistently with the following output (including stack traces):

Established TCP socket on 51419
<===[JENKINS REMOTING CAPACITY]===>channel started
Executing Maven:  -N -B -f drive:\path\to\pom.xml clean install
java.lang.NullPointerException
	at jenkins.maven3.agent.Maven32Main.launch(Maven32Main.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:133)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:68)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Started by upstream project "InteropServer-3.0-build" build number 19
originally caused by:
 Started by user Jonathan Hyry
Finished: ABORTED
FATAL: java.lang.reflect.InvocationTargetException
java.io.IOException: java.lang.reflect.InvocationTargetException
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:173)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:68)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to Channel to Maven [C:\Program Files\Java\jdk1.8.0_112/bin/java, -Djava.awt.headless=true, -cp, C:\Program Files (x86)\Jenkins\plugins\maven-plugin\WEB-INF\lib\maven33-agent-1.8.1.jar;C:\Users\jhyry\Application\apache-maven-3.3.9\boot\plexus-classworlds-2.5.2.jar;C:\Users\jhyry\Application\apache-maven-3.3.9/conf/logging, jenkins.maven3.agent.Maven33Main, C:\Users\jhyry\Application\apache-maven-3.3.9, C:\Program Files (x86)\Jenkins\war\WEB-INF\lib\remoting-3.2.jar, C:\Program Files (x86)\Jenkins\plugins\maven-plugin\WEB-INF\lib\maven33-interceptor-1.8.1.jar, C:\Program Files (x86)\Jenkins\plugins\maven-plugin\WEB-INF\lib\maven3-interceptor-commons-1.8.1.jar, 51419](Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1537)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
	at hudson.remoting.Channel.call(Channel.java:822)
	at hudson.maven.ProcessCache$MavenProcess.call(ProcessCache.java:161)
	at hudson.maven.MavenBuild$MavenBuildExecution.doRun(MavenBuild.java:880)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1729)
	at hudson.maven.MavenBuild.run(MavenBuild.java:270)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:133)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:68)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: java.lang.NullPointerException
	at jenkins.maven3.agent.Maven32Main.launch(Maven32Main.java:189)
	... 14 more
Caused by: java.lang.NullPointerException
	at jenkins.maven3.agent.Maven32Main.launch(Maven32Main.java:186)
	... 14 more
channel stopped

The changes I'm proposing are just an idea about how to fix it.
I've never done development on Jenkins, Jenkins plugins, Maven, or any Maven plugins before, so I'm not intimately familiar with any additional initialization steps that might be required for Launcher.
From my perspective, this is a relatively simple issue with a simple fix.

Hopefully this helps.

Thanks,

Jon

2016-12-16 22:55 UTC, eljonny commented
Let me know if you prefer the committer to squash... I know this is a feature in GitHub now (maintainer can squash all commits in a PR) but if you prefer, I'll do it.

Cheers,

Jon

2017-05-23 09:06 UTC, oleg-nenashev commented
@jenkinsci/code-reviewers @aheritier Since there is a new release incoming for #11, it would be great to get it reviewed as well

2017-05-23 09:12 UTC, oleg-nenashev requested changes
Exceptions need to be wrapped somehow. Or a new methods is required

#11 will need to include the same fix for Maven 3.5
Maybe it makes sense to create a MainBase class and to move the shared logic there

2017-05-23 09:12 UTC, oleg-nenashev commented on maven-agent/src/main/java/hudson/maven/agent/Main.java
> +    public static int launch(String[] args)
🐛 It breaks the compatibility of the public method. Ideally there should be a new one with better interface

2024-07-11 00:00 UTC, closed without merging